services:
  vanshaavali-database:
    image: neo4j:latest
    container_name: vanshaavali-graph
    environment:
      - NEO4J_AUTH=neo4j/PASSWORD
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_export_file_enabled=true
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_exports:/var/lib/neo4j/import